version: 2

updates:
  # GitHub Actions dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "build(deps)"

  # Gradle dependencies
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - gradle
    commit-message:
      prefix: "build(deps)"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
      kotest:
        patterns:
          - "io.kotest*"
      kotlinx:
        patterns:
          - "org.jetbrains.kotlinx*"
